import sys
print(f"CERT DEBUG: sys.executable: {sys.executable}")
print(f"CERT DEBUG: sys.path: {sys.path}")

try:
    from reportlab.lib.pagesizes import landscape, letter
    from reportlab.pdfgen import canvas
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    REPORTLAB_AVAILABLE = True
except ImportError as e:
    REPORTLAB_AVAILABLE = False
    print(f"WARNING: 'reportlab' module not found. Error: {e}")

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except Exception as e:
    FPDF_AVAILABLE = False
    print(f"WARNING: 'fpdf' module not found. Error: {e}")

import io
from datetime import datetime

def generate_certificate_pdf(user_name: str, course_name: str, completion_date: str = None) -> io.BytesIO:
    """
    Generates a PDF certificate in memory and returns the BytesIO buffer.
    """
    print(f"DEBUG: generate_certificate_pdf called for {user_name}, {course_name}")
    
    if not REPORTLAB_AVAILABLE and not FPDF_AVAILABLE:
        print("DEBUG: No PDF library available")
        raise Exception("Certificate generation service is unavailable (missing dependencies).")
        
    if completion_date is None:
        completion_date = datetime.now().strftime("%B %d, %Y")

    buffer = io.BytesIO()
    
    try:
        if REPORTLAB_AVAILABLE:
            print("DEBUG: Using ReportLab")
            # --- ReportLab Implementation ---
            c = canvas.Canvas(buffer, pagesize=landscape(letter))
            width, height = landscape(letter)
            
            # Background / Border
            c.setStrokeColor(colors.darkblue)
            c.setLineWidth(5)
            c.rect(0.5*inch, 0.5*inch, width-1*inch, height-1*inch)
            
            c.setStrokeColor(colors.gold)
            c.setLineWidth(2)
            c.rect(0.6*inch, 0.6*inch, width-1.2*inch, height-1.2*inch)

            # Header
            c.setFont("Helvetica-Bold", 36)
            c.drawCentredString(width / 2, height - 2*inch, "Certificate of Completion")
            
            c.setFont("Helvetica", 18)
            c.drawCentredString(width / 2, height - 3*inch, "This certifies that")
            
            # User Name
            c.setFont("Helvetica-BoldOblique", 30)
            c.setFillColor(colors.darkblue)
            c.drawCentredString(width / 2, height - 4*inch, user_name)
            
            # Body
            c.setFillColor(colors.black)
            c.setFont("Helvetica", 18)
            c.drawCentredString(width / 2, height - 5*inch, "has successfully completed the course")
            
            # Course Name
            c.setFont("Helvetica-Bold", 24)
            c.drawCentredString(width / 2, height - 6*inch, course_name)
            
            # Date
            c.setFont("Helvetica", 14)
            c.drawCentredString(width / 2, height - 7*inch, f"Date: {completion_date}")
            
            # Footer / Brand
            c.setFont("Helvetica-Oblique", 12)
            c.setFillColor(colors.gray)
            c.drawCentredString(width / 2, 1*inch, "Generated by EvoCode Learning Platform")

            c.showPage()
            c.save()
            print("DEBUG: ReportLab generation successful")
            
        elif FPDF_AVAILABLE:
            print("DEBUG: Using FPDF")
            # --- FPDF Implementation (Fallback) ---
            pdf = FPDF(orientation='L', unit='mm', format='Letter')
            pdf.add_page()
            width, height = 279.4, 215.9 # Letter landscape in mm
            
            # Border
            pdf.set_line_width(2)
            pdf.set_draw_color(0, 0, 139) # Dark Blue
            pdf.rect(12, 12, width-24, height-24)
            
            pdf.set_line_width(1)
            pdf.set_draw_color(255, 215, 0) # Gold
            pdf.rect(15, 15, width-30, height-30)
            
            # Header
            pdf.set_font("Arial", 'B', 36)
            pdf.set_xy(0, 50)
            pdf.cell(width, 10, "Certificate of Completion", 0, 1, 'C')
            
            pdf.set_font("Arial", '', 18)
            pdf.set_xy(0, 70)
            pdf.cell(width, 10, "This certifies that", 0, 1, 'C')
            
            # User Name
            pdf.set_font("Arial", 'BI', 30)
            pdf.set_text_color(0, 0, 139)
            pdf.set_xy(0, 90)
            pdf.cell(width, 10, user_name, 0, 1, 'C')
            
            # Body
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Arial", '', 18)
            pdf.set_xy(0, 115)
            pdf.cell(width, 10, "has successfully completed the course", 0, 1, 'C')
            
            # Course Name
            pdf.set_font("Arial", 'B', 24)
            pdf.set_xy(0, 135)
            pdf.cell(width, 10, course_name, 0, 1, 'C')
            
            # Date
            pdf.set_font("Arial", '', 14)
            pdf.set_xy(0, 160)
            pdf.cell(width, 10, f"Date: {completion_date}", 0, 1, 'C')
            
            # Footer
            pdf.set_font("Arial", 'I', 12)
            pdf.set_text_color(128, 128, 128)
            pdf.set_xy(0, 190)
            pdf.cell(width, 10, "Generated by EvoCode Learning Platform", 0, 1, 'C')
            
            # Output to string/bytes
            pdf_output = pdf.output(dest='S')
            # FPDF returns bytearray or string depending on version. 
            # Modern fpdf2 might need dest='S' for bytes? Usually dest='S' returns string (latin-1).
            # Better: dest='S'.encode('latin-1') if py3.
            # Let's try to handle bytes conversion carefully.
            if isinstance(pdf_output, str):
                buffer.write(pdf_output.encode('latin-1'))
            else:
                buffer.write(pdf_output)
            print("DEBUG: FPDF generation successful")

    except Exception as e:
        print(f"ERROR in generate_certificate_pdf: {e}")
        import traceback
        traceback.print_exc()
        raise e
        
    buffer.seek(0)
    return buffer
